### ISSUE TITLE
[Discussion] Implementation in Go

### ISSUE THREAD

**Issue by peterstace** [lemire/SIMDCompressionAndIntersection#21]
I'm interested in using SIMD compression and intersection from within a Go program. Do you have any tips for implementing this library in Go? Do you have plans for implementing the algorithms in any other languages?

Also, do you know the extent to which your library is being used in industry?

**Comment by lemire** [comment]
For this particular library, I am not aware of any existing Go wrappers, however another library (simdcomp) has a basic Go interface https://github.com/lemire/simdcomp

There is also a pure Go version...
https://github.com/zhenjl/encoding

You might also be interested in Roaring Bitmaps which have Go libraries... 

http://roaringbitmap.org

As far as industry use of the current github repo, I expect it to be small because it is a research library... However, an example of an industry adaptation was published in Information Systems...

https://arxiv.org/abs/1611.05428

The code is open source.

**Comment by lemire** [comment]
I'll close the issue, reopen if needed.
